spring:
  datasource:
    url: "jdbc:mysql://localhost/todolist" # jdbc(java database collector): 데이터베이스 선택
    username: "root"
    password: "nayoung0626."
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Spring이 시작할 때 DB table과 객체의 mapping이 다르면 어떻게 처리할지:
    properties:
      hibernate:
        show_sql: true  # 실행했을 때, 실행한 SQL문을 보여줄지
        format_sql: true  # SQL문을 보여줄 때, 깔끔하게 formating할지
        dialect: org.hibernate.dialect.MySQL8Dialect  # 조금씩 다른 SQL을 해당 DB에 맞게 수정해줌
